export const SET_FULL_NAME_BILLING = 'SET_FULL_NAME_BILLING'
export const SET_EMAIL_BILLING = 'SET_EMAIL_BILLING'

export const SET_GEO_ADDRESS_BILLING = 'SET_GEO_ADDRESS_BILLING'
export const SET_GEO_ADDRESS_MORE_BILLING = 'SET_GEO_ADDRESS_MORE_BILLING'
export const SET_GEO_CITY_BILLING = 'SET_GEO_CITY_BILLING'
export const SET_GEO_COUNTRY_CLICK_BILLING = 'SET_GEO_COUNTRY_CLICK_BILLING'
export const SET_GEO_COUNTRY_TYPING_BILLING = 'SET_GEO_COUNTRY_TYPING_BILLING'
export const SET_GEO_ZIP_BILLING = 'SET_GEO_ZIP_BILLING'

export const DISPATCH_GEODATA_CITY_BILLING = 'DISPATCH_GEODATA_CITY_BILLING'
export const DISPATCH_GEODATA_COUNTRY_BILLING = 'DISPATCH_GEODATA_COUNTRY_BILLING'
export const DISPATCH_GEODATA_POSTAL_CODE_BILLING = 'DISPATCH_GEODATA_POSTAL_CODE_BILLING'

export const SET_GEO_AS_SHIPPING = 'SET_GEO_AS_SHIPPING'