export const SET_FULL_NAME = 'SET_FULL_NAME'
export const SET_PHONE = 'SET_PHONE'
export const SET_EMAIL = 'SET_EMAIL'

export const SET_GEO_ADDRESS = 'SET_GEO_ADDRESS'
export const SET_GEO_ADDRESS_MORE = 'SET_GEO_ADDRESS_MORE'
export const SET_GEO_CITY = 'SET_GEO_CITY'
export const SET_GEO_COUNTRY_CLICK = 'SET_GEO_COUNTRY_CLICK'
export const SET_GEO_COUNTRY_TYPING = 'SET_GEO_COUNTRY_TYPING'
export const SET_GEO_ZIP = 'SET_GEO_ZIP'

export const SET_CARD_HOLDER_NAME = 'SET_CARD_HOLDER_NAME'
export const SET_CARD_NUMBER = 'SET_CARD_NUMBER'
export const SET_CARD_EXPIRE_DATE = 'SET_CARD_EXPIRE_DATE'
export const SET_CARD_SECURITY_CODE = 'SET_CARD_SECURITY_CODE'

export const DISPATCH_GEODATA_CITY = 'DISPATCH_GEODATA_CITY'
export const DISPATCH_GEODATA_COUNTRY = 'DISPATCH_GEODATA_COUNTRY'
export const DISPATCH_GEODATA_POSTAL_CODE = 'DISPATCH_GEODATA_POSTAL_CODE'