export const SET_FULL_NAME = 'SET_FULL_NAME'
export const SET_PHONE = 'SET_PHONE'
export const SET_EMAIL = 'SET_EMAIL'

export const SET_GEO_ADDRESS = 'SET_GEO_ADDRESS'
export const SET_GEO_ADDRESS_MORE = 'SET_GEO_ADDRESS_MORE'
export const SET_GEO_CITY = 'SET_GEO_CITY'
export const SET_GEO_COUNTRY = 'SET_GEO_COUNTRY'
export const SET_GEO_ZIP = 'SET_GEO_ZIP'

export const SET_CARD_HOLDER_NAME = 'SET_CARD_HOLDER_NAME'
export const SET_CARD_NUMBER = 'SET_CARD_NUMBER'
export const SET_CARD_EXPIRE_DATE = 'SET_CARD_EXPIRE_DATE'
export const SET_CARD_SECURITY_CODE = 'SET_CARD_SECURITY_CODE'