export const SET_CARD_HOLDER_NAME = 'SET_CARD_HOLDER_NAME'
export const SET_CARD_NUMBER = 'SET_CARD_NUMBER'
export const SET_CARD_EXPIRE_DATE = 'SET_CARD_EXPIRE_DATE'
export const SET_CARD_SECURITY_CODE = 'SET_CARD_SECURITY_CODE'