export const SET_FULL_NAME_SHIPPING = 'SET_FULL_NAME_SHIPPING'
export const SET_PHONE_SHIPPING = 'SET_PHONE_SHIPPING'

export const SET_GEO_ADDRESS_SHIPPING = 'SET_GEO_ADDRESS_SHIPPING'
export const SET_GEO_ADDRESS_MORE_SHIPPING = 'SET_GEO_ADDRESS_MORE_SHIPPING'
export const SET_GEO_CITY_SHIPPING = 'SET_GEO_CITY_SHIPPING'
export const SET_GEO_COUNTRY_CLICK_SHIPPING = 'SET_GEO_COUNTRY_CLICK_SHIPPING'
export const SET_GEO_COUNTRY_TYPING_SHIPPING = 'SET_GEO_COUNTRY_TYPING_SHIPPING'
export const SET_GEO_ZIP_SHIPPING = 'SET_GEO_ZIP_SHIPPING'

export const DISPATCH_GEODATA_CITY_SHIPPING = 'DISPATCH_GEODATA_CITY_SHIPPING'
export const DISPATCH_GEODATA_COUNTRY_SHIPPING = 'DISPATCH_GEODATA_COUNTRY_SHIPPING'
export const DISPATCH_GEODATA_POSTAL_CODE_SHIPPING = 'DISPATCH_GEODATA_POSTAL_CODE_SHIPPING'